### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DarkPhoenix2704** [DarkPhoenix2704/discowin-reimagined#2]
Create Documentation

**Comment by angellee177** [comment]
hi @DarkPhoenix2704 , is it solve? i'm interested to give it a try, please assign me if its not solve yet. :)

**Comment by DarkPhoenix2704** [comment]
ok

**Comment by angellee177** [comment]
@DarkPhoenix2704 quick question, do we have image logo for this repo?

**Comment by DarkPhoenix2704** [comment]
Nop. We don't have one

**Comment by angellee177** [comment]
hi @DarkPhoenix2704 , I just push a few scratches for the doc.
I have not finished it yet, can you please review the pull request? 
i think it's good to go because I didn't disturb or change the current Docs.


I need this PR for Hacktoberfest goals too, please help me to review and approve it. :)
and I will finish the docs tomorrow, is that okay for you?

**Comment by DarkPhoenix2704** [comment]
yes

**Comment by angellee177** [comment]
should we close this issue? @DarkPhoenix2704
